/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.model.sql;


import com.revolut.task.model.sql.tables.Account;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = com.revolut.task.model.sql.tables.Account.ACCOUNT;
}
